### ISSUE TITLE
Problems listening for multiple inputs

### ISSUE THREAD

**Issue by mortenboye** [ardera/flutter_gpiod#11]
Trying to listen for inputs from multiple lines simultaneously, causes a few issues.

I have a list of Gpio pin numbers I would like to listen to.
Iterating the list, setting up the lines and listeners, only works for the first pin.

```
for (var pin in _buttonPins) {
    print("setting up pin $pin");
    final line = gpioChip.lines[pin];

    line.requestInput(consumer: "flutter_gpiod", triggers: {SignalEdge.falling, SignalEdge.rising}, activeState: ActiveState.high);
      
    line.onEvent.listen((evt) {
        _handleGPIOEvent(evt, pin);
    });
}
```

It appears that Stream<GlobalSignalEvent> get eventStream does not return a broadcastStream, easy fix.
Now it works for two pins.
Still, six to go.

running gpioinfo:
```
pi@raspberrypi:~ $ gpioinfo
gpiochip0 - 54 lines:
	line   0:      unnamed       unused   input  active-high 
	line   1:      unnamed       unused   input  active-high 
	line   2:      unnamed       unused   input  active-high 
	line   3:      unnamed       unused   input  active-high 
	line   4:      unnamed       unused   input  active-high 
	line   5:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
	line   6:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
	line   7:      unnamed   "spi0 CS1"  output   active-low [used]
	line   8:      unnamed   "spi0 CS0"  output   active-low [used]
	line   9:      unnamed       unused   input  active-high 
	line  10:      unnamed       unused   input  active-high 
	line  11:      unnamed       unused   input  active-high 
	line  12:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
	line  13:      unnamed       unused   input  active-high 
	line  14:      unnamed       unused   input  active-high 
	line  15:      unnamed       unused   input  active-high 
	line  16:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
	line  17:      unnamed       unused   input  active-high 
	line  18:      unnamed       unused   input  active-high 
	line  19:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
	line  20:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
	line  21:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
	line  22:      unnamed       unused   input  active-high 
	line  23:      unnamed       unused   input  active-high 
	line  24:      unnamed       unused   input  active-high 
	line  25:      unnamed       unused   input  active-high 
	line  26:      unnamed "flutter_gpiodaultRouteName" input active-high [used]
...
```
Aside from the consumer name being weird (pointer error?), I guess it looks OK.

What is the correct way to do this?

**Comment by ardera** [comment]
I'll look into it

> It appears that Stream get eventStream does not return a broadcastStream, easy fix.

Yeah, it's basically a `ReceivePort`'s receive stream mapped to `SignalEvent`. Single subscription streams are easy to adapt to broadcast streams, while the other way around is way harder, so I chose to return a single subscription stream. I should probably document this though

> Aside from the consumer name being weird (pointer error?)

I think I'm not zeroing out the consumer field in the internal GPIO request, I'll change that.

**Comment by mortenboye** [comment]
Any advise wrt. how to listen for multiple ports simultaneously ?

**Comment by ardera** [comment]
> Any advise wrt. how to listen for multiple ports simultaneously ?

What do you mean? It should be as simple as configuring them all as input with some non-empty `triggers` and then just listening to each lines `onEvent` stream. I just tested with 2 lines and it works fine, in that case at least. Or do you mean multiple chips?

Btw, I'll push an update soon that'll change the single subscription stream into a broadcast stream. The single subscription stream really has only downsides and I'll update the example so it shows how to get a buffering (= single subscription) stream if necessary.

**Comment by mortenboye** [comment]
When I run this code loop
```
var _buttonPins = [5, 6, 12, 19, 26, 16, 20, 21];

final chips = FlutterGpiod.instance.chips;

// Find the gpio chip
final gpioChip = chips.firstWhere((chip) => chip.label == 'pinctrl-bcm2835');

print("${gpioChip}");

for (var pin in _buttonPins) {
    print("setting up pin $pin");
    final line = gpioChip.lines[pin];

    line.requestInput(consumer: "flutter_gpiod", triggers: {SignalEdge.falling, SignalEdge.rising}, activeState: ActiveState.high);

    line.onEvent.listen((evt) {
        _handleGPIOEvent(evt, pin);
    });
}
```

I get this error
```
flutter: GpiodChip(index: 0, name: 'gpiochip0', label: 'pinctrl-bcm2835', numLines: 54)
flutter: setting up pin 5
flutter: setting up pin 6
[ERROR:engine/src/flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:710:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
#3      _ReceivePortImpl.listen (dart:isolate-patch/isolate_patch.dart:87:31)
#4      CastStream.listen (dart:_internal/async_cast.dart:17:17)
#5      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
#6      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
#7      _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
#8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
#9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
#10     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
#11     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
#12     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
#13     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
#14     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
#15     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
#16     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
...
```

**Comment by ardera** [comment]
Yeah that was my bad. It's now a broadcast stream in 0.3.0. (uploaded to pub.dev already)

**Comment by mortenboye** [comment]
Thank you.
