### ISSUE TITLE
RPi 4 Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by kekko7072** [ardera/flutter_gpiod#19]
I have the code running perfectly on RPi 3 B+, now I am running the same code in RPi 4 and I have this error. 

```
Unhandled Exception: Bad state: No element
#0      ListMixin.singleWhere (dart:collection/list.dart:202:5)
#1      GPIO.closeRelay (package:loungeos/src/services/gpio.dart:94:26)
#2      _HomeState.build.<anonymous closure>.<anonymous closure> (package:loungeos/src/views/home.dart:109:57)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#21     _rootRunUnary (dart:async/zone.dart:1370:13)
#22     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#24     _invoke1 (dart:ui/hooks.dart:182:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```
Any ideas?

**Comment by kekko7072** [comment]
RPi 4 requires **`pinctrl-bcm2711`**,  I know it thanks to the command  `print(chips.single.lines.first)`

**Comment by kekko7072** [comment]
You can see it running `pinout` in terminal and then read the `SoC` value.

**Comment by ardera** [comment]
Yeah they changed the name of it recently, someone else already had the issue before: https://github.com/ardera/flutter_gpiod/issues/14

I changed the readme (in the [new location of this package](https://github.com/ardera/flutter_packages/tree/main/packages/flutter_gpiod), please use that instead for reporting issues in the future) to indicate that but I think it's not yet visible in pub.dev because it's a prerelease
